/**
 * ============================================================================
 * [OUTPUT]: 对外提供 templates 数组
 * [POS]: 模板预设配置，每个模板是一组配置的组合
 * [PROTOCOL]: 变更时更新此头部，然后检查 CLAUDE.md
 * ============================================================================
 */

export const templates = [
    {
        id: 'default',
        name: '默认',
        description: '经典渐变背景 + 圆角卡片',
        config: {
            theme: 'radiant-1',
            mdStyle: 'prose',
            padding: 33,
            borderRadius: 15,
            shadow: 'soft',
            width: 540,
        },
        preview: {
            background: 'linear-gradient(135deg, #667eea, #764ba2)',
            cardBg: '#ffffff',
            textColor: '#1a1a2e',
        },
    },
    {
        id: 'transparent',
        name: '透明',
        description: '淡色背景 + 半透明卡片',
        config: {
            theme: 'solid-1',
            mdStyle: 'prose',
            padding: 33,
            borderRadius: 15,
            shadow: 'ambient',
            width: 540,
        },
        preview: {
            background: '#f8f9fa',
            cardBg: '#ffffff',
            textColor: '#1a1a2e',
        },
    },
    {
        id: 'quote',
        name: '金句',
        description: '温暖渐变 + 大字引言',
        config: {
            theme: 'radiant-5',
            mdStyle: 'classic',
            padding: 40,
            borderRadius: 20,
            shadow: 'elevated',
            width: 540,
        },
        preview: {
            background: 'linear-gradient(135deg, #fa709a, #fee140)',
            cardBg: '#ffffff',
            textColor: '#1a1a2e',
        },
    },
    {
        id: 'excerpt',
        name: '书摘',
        description: '淡雅风格 + 优雅排版',
        config: {
            theme: 'radiant-11',
            mdStyle: 'prose',
            padding: 36,
            borderRadius: 12,
            shadow: 'soft',
            width: 540,
        },
        preview: {
            background: 'linear-gradient(135deg, #e0c3fc, #8ec5fc)',
            cardBg: '#ffffff',
            textColor: '#1a1a2e',
        },
    },
    {
        id: 'memo',
        name: '备忘录',
        description: '简洁白底 + GitHub 排版',
        config: {
            theme: 'solid-2',
            mdStyle: 'github',
            padding: 24,
            borderRadius: 10,
            shadow: 'medium',
            width: 540,
        },
        preview: {
            background: '#e2e8f0',
            cardBg: '#ffffff',
            textColor: '#1a1a2e',
        },
    },
    {
        id: 'bento',
        name: '便当',
        description: '鲜艳渐变 + 紧凑布局',
        config: {
            theme: 'radiant-9',
            mdStyle: 'classic',
            padding: 20,
            borderRadius: 16,
            shadow: 'hard',
            width: 540,
        },
        preview: {
            background: 'linear-gradient(135deg, #f6d365, #fda085)',
            cardBg: '#ffffff',
            textColor: '#1a1a2e',
        },
    },
    {
        id: 'noir',
        name: '黑日',
        description: '暗黑风格 + 翡翠排版',
        config: {
            theme: 'dark-1',
            mdStyle: 'emerald',
            padding: 33,
            borderRadius: 15,
            shadow: 'glow-purple',
            width: 540,
        },
        preview: {
            background: 'linear-gradient(135deg, #0c0c1d, #1a1a3e)',
            cardBg: '#1e293b',
            textColor: '#e2e8f0',
        },
    },
    {
        id: 'frame',
        name: '框界',
        description: '网格纹理 + 方正布局',
        config: {
            theme: 'dark-3',
            mdStyle: 'classic',
            padding: 28,
            borderRadius: 8,
            shadow: 'sharp',
            width: 540,
        },
        preview: {
            background: 'linear-gradient(135deg, #232526, #414345)',
            cardBg: '#1e293b',
            textColor: '#e2e8f0',
        },
    },
    {
        id: 'minimal',
        name: '简约',
        description: '极简白底 + 无阴影',
        config: {
            theme: 'solid-1',
            mdStyle: 'prose',
            padding: 40,
            borderRadius: 0,
            shadow: 'none',
            width: 540,
        },
        preview: {
            background: '#f8f9fa',
            cardBg: '#ffffff',
            textColor: '#1a1a2e',
        },
    },
    {
        id: 'story',
        name: '故事',
        description: '粉色渐变 + 柔和圆角',
        config: {
            theme: 'radiant-7',
            mdStyle: 'prose',
            padding: 36,
            borderRadius: 24,
            shadow: 'elevated',
            width: 540,
        },
        preview: {
            background: 'linear-gradient(135deg, #ff9a9e, #fecfef, #fdfcfb)',
            cardBg: '#ffffff',
            textColor: '#1a1a2e',
        },
    },
    {
        id: 'glass',
        name: '玻璃',
        description: '玻璃拟态 + 轻柔高光',
        config: {
            theme: 'mesh-2',
            mdStyle: 'prose',
            padding: 32,
            borderRadius: 18,
            shadow: 'soft',
            width: 540,
        },
        preview: {
            background: 'linear-gradient(135deg, #7f7fd5, #86a8e7, #91eae4)',
            cardBg: 'rgba(255, 255, 255, 0.7)',
            textColor: '#1a1a2e',
        },
    },
    {
        id: 'brutal',
        name: '粗野',
        description: '高对比 + 硬朗阴影',
        config: {
            theme: 'solid-3',
            mdStyle: 'classic',
            padding: 28,
            borderRadius: 6,
            shadow: 'sharp',
            width: 540,
        },
        preview: {
            background: '#09090b',
            cardBg: '#f8fafc',
            textColor: '#0f172a',
        },
    },
    {
        id: 'editorial',
        name: '杂志',
        description: '编辑排版 + 大留白',
        config: {
            theme: 'solid-2',
            mdStyle: 'classic',
            padding: 44,
            borderRadius: 6,
            shadow: 'ambient',
            width: 540,
        },
        preview: {
            background: '#e2e8f0',
            cardBg: '#ffffff',
            textColor: '#1f2937',
        },
    },
    {
        id: 'code',
        name: '代码',
        description: '深色代码卡片',
        config: {
            theme: 'dark-6',
            mdStyle: 'github',
            padding: 28,
            borderRadius: 12,
            shadow: 'medium',
            width: 540,
        },
        preview: {
            background: 'linear-gradient(135deg, #141e30, #243b55)',
            cardBg: '#0f172a',
            textColor: '#e2e8f0',
        },
    },
    {
        id: 'midnight',
        name: '暗黑极简',
        description: '低饱和暗色 + 细腻质感',
        config: {
            theme: 'solid-3',
            mdStyle: 'prose',
            padding: 34,
            borderRadius: 12,
            shadow: 'ambient',
            width: 540,
        },
        preview: {
            background: '#09090b',
            cardBg: '#1f2937',
            textColor: '#e5e7eb',
        },
    },
    {
        id: 'vapor',
        name: '蒸汽波',
        description: '霓虹渐变 + 复古氛围',
        config: {
            theme: 'mesh-1',
            mdStyle: 'classic',
            padding: 30,
            borderRadius: 18,
            shadow: 'glow-pink',
            width: 540,
        },
        preview: {
            background: 'linear-gradient(45deg, #f953c6, #b91d73, #e91e63)',
            cardBg: '#ffffff',
            textColor: '#1a1a2e',
        },
    },
    {
        id: 'social',
        name: '社媒',
        description: '社媒截图风 + 清爽卡片',
        config: {
            theme: 'solid-1',
            mdStyle: 'github',
            padding: 26,
            borderRadius: 14,
            shadow: 'soft',
            width: 540,
        },
        preview: {
            background: '#f8f9fa',
            cardBg: '#ffffff',
            textColor: '#0f172a',
        },
    },
    {
        id: 'notion',
        name: 'Notion',
        description: '文档风格 + 轻量留白',
        config: {
            theme: 'solid-1',
            mdStyle: 'prose',
            padding: 38,
            borderRadius: 8,
            shadow: 'ambient',
            width: 540,
        },
        preview: {
            background: '#f8f9fa',
            cardBg: '#ffffff',
            textColor: '#1f2937',
        },
    },
    {
        id: 'news',
        name: '新闻',
        description: '新闻排版 + 高可读性',
        config: {
            theme: 'solid-2',
            mdStyle: 'classic',
            padding: 42,
            borderRadius: 6,
            shadow: 'soft',
            width: 540,
        },
        preview: {
            background: '#e2e8f0',
            cardBg: '#ffffff',
            textColor: '#0f172a',
        },
    },
    {
        id: 'poster',
        name: '海报',
        description: '大字海报 + 强对比',
        config: {
            theme: 'mesh-4',
            mdStyle: 'classic',
            padding: 30,
            borderRadius: 22,
            shadow: 'elevated',
            width: 540,
        },
        preview: {
            background: 'linear-gradient(135deg, #8e2de2, #4a00e0)',
            cardBg: '#ffffff',
            textColor: '#1a1a2e',
        },
    },
]
